repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.255"
    hooks:
      - id: ruff
        args: ["--ignore=I001,E402,E721,E731,E741,F722,E501"]
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.3
    hooks:
      - id: nbqa-black
      # - id: nbqa-ruff
      # exclude: ["^notebooks/dev/", "^jbook/"]
      # args: [
      #     "--ignore=I001,F821,F541",
      #     # "--nbqa-exclude=^notebooks/dev/,jbook/",
      #     # "--nbqa-exclude=jbook/",
      #   ]
