repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.255"
    hooks:
      - id: ruff
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.3
    hooks:
      - id: nbqa-black
      - id: nbqa-ruff
        args: ["--ignore=I001", "--nbqa-exclude=notebooks/dev/"]
